apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: ${NAME}
spec:
  designerFlowsOperationMode: disabled
  license:
    accept: true
    license: L-APEH-BPUCJK
    use: CloudPakForIntegrationNonProduction
  tracing:
    enabled: ${TRACING_ENABLED}
    namespace: ${TRACING_NS}
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: https
  useCommonServices: true
  version: 11.0.0.10-r1
  adminServerSecure: true
  pod:
    containers:
      runtime:
        image: ${IMAGE}
        imagePullPolicy: Always
