apiVersion: v1
kind: Template
metadata:
  name: ace-secret
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    name: ${SECRET_NAME}
    namespace: ${NAMESPACE}
  type: Opaque
  data:
    configuration: ${ACE_SERVER_CERT_KS_OR_TS}
parameters:
  - name: SECRET_NAME
  - name: NAMESPACE
  - name: ACE_SERVER_CERT_KS_OR_TS